# Generated by Django 4.2.7 on 2024-02-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='portada',
            field=models.ImageField(null=True, upload_to='media/descarga.jpeg'),
        ),
    ]
