# Generated by Django 4.2.7 on 2024-02-07 12:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ficheros',
            field=models.FileField(null=True, upload_to='catalog/media/ficheros'),
        ),
        migrations.AddField(
            model_name='book',
            name='video',
            field=models.FileField(null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='book',
            name='portada',
            field=models.ImageField(null=True, upload_to='catalog/media/imagenes/'),
        ),
    ]
