# Generated by Django 4.2.7 on 2024-02-17 10:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_ficheros_book_video_alter_book_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_generate_pdf', 'Generate PDF'), ('permiso1', 'Crear Usuario'))},
        ),
        migrations.AlterField(
            model_name='book',
            name='ficheros',
            field=models.FileField(null=True, upload_to='catalog/media/pdf/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='video',
            field=models.FileField(null=True, upload_to='catalog/media/videos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
