# Generated by Django 4.2.7 on 2024-02-17 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_perfiles_alter_bookinstance_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
