# Generated by Django 4.2.7 on 2024-02-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_perfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'), ('can_generate_pdf', 'Generate PDF'), ('permiso1', 'Crear Usuario'), ('permiso2', 'Crear Perfil Usuario'), ('permiso3', 'Gestion Mensajes'))},
        ),
        migrations.AddField(
            model_name='perfiles',
            name='localidad',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
