# Generated by Django 4.2.7 on 2024-02-20 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_bookinstance_options_perfiles_localidad'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfiles',
        ),
    ]
