# Generated by Django 4.2.7 on 2024-02-20 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('catalog', '0013_perfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(max_length=50)),
                ('destinatario', models.CharField(max_length=50)),
                ('cuerpo_mensaje', models.CharField(max_length=50)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
