# Generated by Django 4.2.7 on 2024-02-20 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_alter_mensajes_destinatario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mensajes',
        ),
    ]
